[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { version = "0.1.0", path = "../common" }
gloo-net = "0.7.0"
wasm-bindgen = "0.2.121"
yew = { version = "0.23.0", features = ["csr"] }
serde.workspace = true
yew-router = "0.20.0"
gloo-timers = "0.3"
serde_json = { workspace = true }

web-sys = { version = "0.3.98", features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "DomTokenList",
    "HtmlSelectElement",
    "Blob",
    "Url",
    "Navigator",
    "Clipboard"
] }

js-sys = "0.3"
lucide-yew = { version = "3.11.0", features = ["all-icons"] }
