PORT = 3000
CACHE_ITEMS_MAX = 10
DB_NAME = "database.sqlite"
AZIMUT_MAX = 360.0
AZIMUT_MIN = 0.0
SEPARATION_MIN = 1.0
TRANSPORT_SPEED_MIN = 0.514
TRANSPORT_SPEED_MAX = 6.173
ECHO_DEPTH_MIN = 1.0
ECHO_DEPTH_MAX = 6000.0
ECHO_PULSE_MIN = 1.0
ECHO_PULSE_MAX = 20.0
ECHO_UMBRAL_MIN = 10.0
ECHO_UMBRAL_MAX = 90.0
SOUND_SPEED_MIN = 1450.0
SOUND_SPEED_MAX = 1500.0
ADMIN_PASS = "Magicpass2"
DB_NAME = "database.sqlite"
