PORT = 3000
DB_NAME = "database.sqlite"

# Capacidad maxima del cache
CACHE_ITEMS_MAX = 10
    # Agiliza la simulacion, almacenando calculos parciales de la misma
    # Configurar en base a la RAM disponible. Se puede estimar que cada item, ocupara lo mismo que un geotiff.

# Pass utilizada para acceder al CLI.
ADMIN_PASS = "Magicpass2" 
    # Requiere reinicar el servidor, para que se aplique.
    
MAPTILER_API_KEY = "EVEAYM1Cx9nGoDR5OVX6"

# Directorio donde se almacenan los archivos. (geofiff)
# FILE_UPLOAD_PATH = "./uploads"
    # Descomentar y cambiarlo hara que dejen de funcionar los proyectos actuales.
    # Requiriendo volver a subirlos.

# Parametros limite, usados para las simulaciones
AZIMUT_MAX = 360.0
AZIMUT_MIN = 0.0
SEPARATION_MIN = 1.0
TRANSPORT_SPEED_MIN = 0.514
TRANSPORT_SPEED_MAX = 6.173
ECHO_DEPTH_MIN = 1.0
ECHO_DEPTH_MAX = 6000.0
ECHO_PULSE_MIN = 1.0
ECHO_PULSE_MAX = 20.0
ECHO_UMBRAL_MIN = 10.0
ECHO_UMBRAL_MAX = 90.0
SOUND_SPEED_MIN = 1450.0
SOUND_SPEED_MAX = 1500.0
    # Se debe reiniciar el servidor, para que se apliquen.

# Nombre en donde se almacenaran los LOGS.
LOG_FILE_NAME = "logs.txt"
# Criterio para determinar que se deben loggear en el archivo
LOGGING_TYPE = 1
    # Debug = 0,
    # Info  = 1,
    # Warn  = 2,
    # Error = 3,